"""File 11: synthesizing the agent structure itself — state-threading DSL.

Files 6–9 hardcoded the mental machinery in the interpreter: unfold_scene /
_step_belief know to run the policy on a believed grid, diff the frames and
replay the move on the actual grid, and mk_agent_scene fixes the
(belief, desire) product type.  Stitch can only compress what appears in
program trees, so the agent *structure* could never be discovered — only its
parameters.

Here the interpreter shrinks to one purely mechanical operation:

  unfold_state(g, T, sf)    state = (world, model), s0 = (g, copy(g))
                            each frame: s <- sf(s); render the world channel

and everything else moves into program space, built from combinators that are
physical or structural, never mental:

  compose_s(a, b)  :: sfn, sfn -> sfn    sequence two state transitions
  on_world(f)      :: fn -> sfn          f acts on the world channel
  on_model(f)      :: fn -> sfn          f acts on the model channel
  sync_w(v)        :: int -> sfn         copy value v's position from model to world
  wall_at(r, c)    :: int, int -> fn     a wall (3) appears at (r, c)
  step / optimize / neg_dist / compose   physics + gradient-following

The model channel starts as a copy of the world and is never rendered.
Nothing forces "belief" anywhere: a program that ignores the model channel is
ordinary physics.

Expected solutions (one shared DSL across the whole curriculum):

  physics  (4 nodes):  (on_world (step v d))
  desire   (6 nodes):  (on_world (optimize (neg_dist gv) av))
  belief  (12 nodes):  (compose_s (on_model (compose (wall_at r c)
                                             (optimize (neg_dist gv) av)))
                                  (sync_w av))

The belief program IS the believe-step that file9's interpreter performed in
_step_belief, now written in the object language: modify a private copy of
the world, run the policy on it, commit the resulting move to the real world.
av appears twice — in optimize (who acts on the model) and in sync_w (whose
move is committed to the world) — the structural signature of agency.
The hoped-for stitch discovery is the agent type constructor:

  fn_agent($r, $c, $gv, $av) =
    (compose_s (on_model (compose (wall_at $r $c) (optimize (neg_dist $gv) $av)))
               (sync_w $av))

so agents and inanimate objects end up encoded differently because
compression found that distinction, not because the interpreter assumed it.

Cost note: with content-aware Q (av, gv visible in frame 0 → logp 0), the
12-node belief program costs ≈12.6 nats — the same budget window (~7) as
file9's 8-node solutions.  The phantom-wall coordinates are the only
full-price ints.

Run:
  python file11.py            # full run
  python file11.py --smoke    # tiny corpus, short timeouts (plumbing check)
"""

import sys
import re as _re
from collections import Counter
from copy import deepcopy

import numpy as np

from ecd import Deltas, Delta, ECD, normalize, mat_key
from dsl import (
    sfn, fn, util, direction,
    RIGHT, LEFT, UP, DOWN,
    compose_s, on_world, on_model, sync_w, wall_at,
    compose, step, optimize, neg_distance, id_fn,
    unfold_state, tr,
)

# ── Configuration ──────────────────────────────────────────────────────────────
# (agent_val, goal_val) combos: vary both so stitch discovers both as holes
COMBOS = [(1, 2), (1, 5), (4, 2), (4, 5)]
SIZE   = 5
DIRS   = {'right': RIGHT, 'left': LEFT, 'up': UP, 'down': DOWN}


# ── Task generation ────────────────────────────────────────────────────────────
# All tasks are generated by simulating ground-truth programs through the SAME
# unfold_state the searcher uses, so every task is solvable by construction.

def _agent_pos(frame, av):
    pos = np.argwhere(frame == av)
    return (int(pos[0][0]), int(pos[0][1])) if len(pos) else None


def _physically_explainable(x, g):
    "True if x is reproduced by a single on_world(step) or on_world(optimize)."
    T = x.shape[0]
    vals = [int(v) for v in np.unique(g) if v != 0]
    for v in vals:
        for d in DIRS.values():
            try:
                if np.array_equal(unfold_state(g, T, on_world(step(v, d))), x):
                    return True
            except Exception:
                pass
        for u in vals:
            if u == v:
                continue
            try:
                if np.array_equal(unfold_state(g, T, on_world(optimize(neg_distance(u), v))), x):
                    return True
            except Exception:
                pass
    return False


def make_physics_tasks(n, size=SIZE, vals=(1, 4), seed=0):
    "Objects sliding ballistically: ground truth (on_world (step v d))."
    rng = np.random.default_rng(seed)
    tasks = []
    while len(tasks) < n:
        v     = int(rng.choice(vals))
        dname = str(rng.choice(list(DIRS)))
        dr, dc = DIRS[dname]
        T = int(rng.integers(4, 6))
        # start position keeping the object in bounds for all T-1 moves
        r_lo, r_hi = max(0, -dr * (T - 1)), min(size - 1, size - 1 - dr * (T - 1))
        c_lo, c_hi = max(0, -dc * (T - 1)), min(size - 1, size - 1 - dc * (T - 1))
        if r_lo > r_hi or c_lo > c_hi:
            continue
        r, c = int(rng.integers(r_lo, r_hi + 1)), int(rng.integers(c_lo, c_hi + 1))
        g = np.zeros((size, size), dtype=int)
        g[r, c] = v
        x = unfold_state(g, T, on_world(step(v, DIRS[dname])))
        tasks.append((x, {'kind': 'physics', 'val': v, 'dir': dname}))
    return tasks


def make_desire_tasks(n_per_combo, combos=COMBOS, size=SIZE, seed=0):
    """Goal-seeking agents: ground truth (on_world (optimize (neg_dist gv) av)).

    Goal is placed off-axis so the BFS path turns — a turning path is not
    reproducible by any constant per-frame step, forcing the desire structure.
    """
    rng = np.random.default_rng(seed)
    tasks = []
    for av, gv in combos:
        made = 0
        while made < n_per_combo:
            ar, ac = int(rng.integers(size)), int(rng.integers(size))
            gr, gc = int(rng.integers(size)), int(rng.integers(size))
            if ar == gr or ac == gc:
                continue
            L = abs(ar - gr) + abs(ac - gc)
            if not (3 <= L <= 5):
                continue
            g = np.zeros((size, size), dtype=int)
            g[ar, ac] = av
            g[gr, gc] = gv
            T = L + 1
            x = unfold_state(g, T, on_world(optimize(neg_distance(gv), av)))
            if x[-1][gr, gc] != av:   # agent must reach the goal by the last frame
                continue
            tasks.append((x, {'kind': 'desire', 'av': av, 'gv': gv}))
            made += 1
    return tasks


def make_belief_tasks(n_per_combo, combos=COMBOS, size=SIZE, seed=0, max_T=8):
    """False-belief agents: the agent detours around a wall that exists only in
    its model.  Ground truth:

      (compose_s (on_model (compose (wall_at pr pc) (optimize (neg_dist gv) av)))
                 (sync_w av))

    The phantom wall is placed on the true-belief BFS path; scenes are rejected
    unless the wall actually causes a detour AND the trajectory is not
    explainable by any single physical program.
    """
    rng = np.random.default_rng(seed)
    tasks = []
    for av, gv in combos:
        made, attempts = 0, 0
        while made < n_per_combo and attempts < 5000:
            attempts += 1
            ar, ac = int(rng.integers(size)), int(rng.integers(size))
            gr, gc = int(rng.integers(size)), int(rng.integers(size))
            if (ar, ac) == (gr, gc) or abs(ar - gr) + abs(ac - gc) < 3:
                continue
            g = np.zeros((size, size), dtype=int)
            g[ar, ac] = av
            g[gr, gc] = gv

            # true-belief trajectory: source of on-path phantom-wall candidates
            direct = unfold_state(g, max_T, on_world(optimize(neg_distance(gv), av)))
            path = [_agent_pos(direct[t], av) for t in range(max_T)]
            inter = [p for p in path if p and p != (ar, ac) and p != (gr, gc)]
            if not inter:
                continue
            pr, pc = inter[int(rng.integers(len(inter)))]

            gt = compose_s(
                on_model(compose(wall_at(pr, pc), optimize(neg_distance(gv), av))),
                sync_w(av))
            x_full = unfold_state(g, max_T, gt)
            t_arrive = next((t for t in range(max_T)
                             if _agent_pos(x_full[t], av) == (gr, gc)), None)
            if t_arrive is None or t_arrive < 3:
                continue
            T = t_arrive + 1
            x = x_full[:T].copy()
            if np.array_equal(x, direct[:T]):     # phantom wall must cause a detour
                continue
            if _physically_explainable(x, g):
                continue
            tasks.append((x, {'kind': 'belief', 'av': av, 'gv': gv, 'pw': (pr, pc)}))
            made += 1
    return tasks


# ── DSL ────────────────────────────────────────────────────────────────────────

def make_core_prims():
    return [
        Delta(compose_s, sfn, [sfn, sfn],       repr='compose_s'),
        Delta(on_world,  sfn, [fn],             repr='on_world'),
        Delta(on_model,  sfn, [fn],             repr='on_model'),
        Delta(sync_w,    sfn, [int],            repr='sync_w'),

        Delta(compose,      fn,   [fn, fn],          repr='compose'),
        Delta(step,         fn,   [int, direction],  repr='step'),
        Delta(optimize,     fn,   [util, int],       repr='optimize'),
        Delta(wall_at,      fn,   [int, int],        repr='wall_at'),
        Delta(id_fn,        fn,                      repr='id_fn'),
        Delta(neg_distance, util, [int],             repr='neg_dist'),

        Delta(RIGHT, direction, repr='right'),
        Delta(LEFT,  direction, repr='left'),
        Delta(UP,    direction, repr='up'),
        Delta(DOWN,  direction, repr='down'),

        *[Delta(i, int, repr=str(i)) for i in range(6)],
    ]


def verify_ground_truth(D, tasks_meta):
    """Re-express each kind's ground truth as a Delta tree (the searcher's own
    encoding) and check it reproduces the task — catches eager/typing mistakes
    in the Delta encoding rather than in the raw python closures."""
    for x, m in tasks_meta:
        if m['kind'] == 'physics':
            prog = f"(on_world (step {m['val']} {m['dir']}))"
        elif m['kind'] == 'desire':
            prog = f"(on_world (optimize (neg_dist {m['gv']}) {m['av']}))"
        else:
            pr, pc = m['pw']
            prog = (f"(compose_s (on_model (compose (wall_at {pr} {pc}) "
                    f"(optimize (neg_dist {m['gv']}) {m['av']}))) (sync_w {m['av']}))")
        tree = tr(D, prog)
        out = unfold_state(x[0], x.shape[0], tree())
        assert np.array_equal(out, x), f"ground truth failed for {m}: {prog}"
    print(f"ground-truth check: {len(tasks_meta)} tasks verified via Delta trees")


# ── Main ───────────────────────────────────────────────────────────────────────

def main(smoke=False):
    n_phys = 2 if smoke else 6
    n_des  = 1 if smoke else 2   # per combo
    # belief needs the most data: 8 solutions split across ~6 equivalent program
    # shapes (wall-before/after compose order, fused vs flattened compose_s, …),
    # so no shape cluster had enough instances for stitch to prefer holes over
    # baked constants (fn_4 baked wall-row 4 and gv 5).  More tasks per combo
    # makes each shape recur with varied (r, c, gv, av), forcing the holes.
    n_bel  = 1 if smoke else 6   # per combo
    per_task_timeout = 10 if smoke else 300
    max_iterations   = 2  if smoke else 10

    print("Generating tasks…")
    phys = make_physics_tasks(n_phys, seed=0)
    des  = make_desire_tasks(n_des, COMBOS, seed=1)
    bel  = make_belief_tasks(n_bel, COMBOS, seed=2)

    # dedupe across the whole corpus (identical mats would skew counts)
    seen, all_tasks = set(), []
    for x, m in phys + des + bel:
        k = mat_key(x)
        if k in seen:
            continue
        seen.add(k)
        all_tasks.append((x, m))

    Xs   = [x for x, _ in all_tasks]
    meta = [m for _, m in all_tasks]
    by_kind = Counter(m['kind'] for m in meta)
    print(f"  {by_kind['physics']} physics, {by_kind['desire']} desire, "
          f"{by_kind['belief']} belief — {len(Xs)} total\n")

    D = Deltas(make_core_prims())
    print(f"DSL: {len(D)} primitives")
    print("  expected belief solution (12 nodes):")
    print("    (compose_s (on_model (compose (wall_at r c) (optimize (neg_dist gv) av)))")
    print("               (sync_w av))")
    print("  expected stitch discovery — the agent type constructor:")
    print("    fn_agent($r,$c,$gv,$av) with $av shared ×2 (optimize + sync_w)\n")

    verify_ground_truth(D, all_tasks)

    print("\nRunning ECD…\n")
    # stitch_iterations=4: the first two abstractions are always claimed by the
    # high-frequency desire fragment (optimize (neg_dist gv) av), which appears
    # in both the desire and belief corpora.  The agent constructor only becomes
    # the best remaining compression AFTER that fragment is extracted, so stitch
    # needs extra passes to reach it.
    Z, rewritten = ECD(
        Xs, D,
        per_task_timeout=per_task_timeout,
        max_iterations=max_iterations,
        max_arity=5,
        stitch_iterations=4,
        root_type=sfn,
    )

    # ── Report ─────────────────────────────────────────────────────────────────
    print(f"\n=== Results ===")
    for kind in ('physics', 'desire', 'belief'):
        ks = [x for x, m in all_tasks if m['kind'] == kind]
        n  = sum(1 for x in ks if mat_key(x) in Z and Z[mat_key(x)] is not None)
        print(f"  {kind:8s}: {n}/{len(ks)}")

    print("\n=== Invented primitives ===")
    if not D.invented:
        print("  (none)")
    for d in D.invented:
        argtypes = ', '.join(str(t) for t in (d.tailtypes or []))
        body_str = str(normalize(deepcopy(d)))
        shared   = {v: c for v, c in Counter(_re.findall(r'\$\d+', body_str)).items() if c > 1}
        print(f"  {d.repr}  [{argtypes}]  -> {d.type}")
        print(f"    body: {body_str}")
        if 'on_model' in body_str and 'sync_w' in body_str:
            print(f"    *** AGENT TYPE CONSTRUCTOR (belief) ***")
            print(f"        policy runs on the model channel, move committed via sync_w")
            if shared:
                shared_str = ', '.join(f'{v} (×{c})' for v, c in shared.items())
                print(f"        shared: {shared_str}  — actor AND committer")
        elif 'optimize' in body_str or 'neg_dist' in body_str:
            print(f"    *** desire fragment (goal-directed motion) ***")
        elif 'step' in body_str:
            print(f"    *** physics fragment ***")

    # Structural census of the belief solutions: programs with ints stripped.
    # If the 7-8 solutions split across several equivalent shapes (e.g. wall_at
    # before vs after optimize inside compose), no single abstraction has enough
    # matches to win — that heterogeneity is what blocks the agent constructor.
    print("\n=== Belief solution shapes ===")
    skeletons = Counter()
    for x, m in all_tasks:
        if m['kind'] != 'belief':
            continue
        k = mat_key(x)
        if k in Z and Z[k] is not None:
            sol = normalize(deepcopy(Z[k]))
            skeletons[_re.sub(r'\b\d+\b', '_', str(sol))] += 1
    for shape, cnt in skeletons.most_common():
        print(f"  ×{cnt}  {shape}")

    print("\n=== Sample solutions ===")
    kind_seen = Counter()
    for x, m in all_tasks:
        # print all belief solutions (to see shape variants); 2 samples otherwise
        if m['kind'] != 'belief' and kind_seen[m['kind']] >= 2:
            continue
        kind_seen[m['kind']] += 1
        k = mat_key(x)
        tag = {k2: v for k2, v in m.items() if k2 != 'kind'}
        if k in Z and Z[k] is not None:
            sol = normalize(deepcopy(Z[k]))
            rw  = rewritten.get(k, '')
            print(f"  [{m['kind']}] {tag}")
            print(f"    found:     {sol}")
            if rw:
                print(f"    rewritten: {rw}")
        else:
            print(f"  [{m['kind']}] {tag}  → unsolved")


if __name__ == '__main__':
    main(smoke='--smoke' in sys.argv)
