"""Multi-scene tasks: k scenes sharing one latent program.

A task used to be one trajectory `x` of shape (T, H, W), and a program solved it
when `unfold(x[0], T, f) == x`.  A single trajectory under-determines its own
program: the corpus is finite and the DSL is not, so for any one scene there is
almost always a shorter program that reproduces it for the wrong reason.  The
phantom-wall belief tasks made this concrete — a literal `(step av down)` in
fork's derive slot reproduced one detour exactly, so search dropped the wall and
`belief_is_wall_based` came out False.  Every such coincidence was previously met
with another hand-written rejection filter in the generator, which is patching a
representation that has infinitely many holes.

The general cure is DreamCoder's own task format: a task is a SET of k scenes,
all generated by the same latent program from different initial grids, and a
program solves the task only if it reproduces EVERY scene.  A fixed shove cannot
reproduce detours from k different start positions; a wall at the wrong
coordinate dies on scene 2.  What the program shares across the scenes is exactly
its literals (the agent/goal values, the phantom-wall coordinate); what varies is
everything the program does not name (where the entities start, how long the
trajectory runs).  So the scene set pins the latents down extensionally, which is
what the rejection filters were trying to do intensionally.

Nothing downstream of the search changes: one task still has one solution
program, so stitch sees the same number of programs over the same library and the
MDL story is untouched.

`Scenes` deliberately exposes NO `__getitem__` and NO `.shape`.  The old code
said `x[0]` for "the initial grid" and `x.shape[0]` for "T" all over the repo; a
container that silently answered those with per-scene data would have introduced
quiet wrong answers instead of loud errors.  Ask for `.rep` (a representative
scene, for viz and for conditioning a recognition model) or iterate.
"""

import hashlib

import numpy as np


class Scenes:
    """k trajectories sharing one latent program.

    Each scene is a (T_i, H, W) int array; T may differ between scenes (the same
    program run to a different arrival time), the grid shape may not.
    """

    __slots__ = ('scenes',)

    def __init__(self, scenes):
        if isinstance(scenes, np.ndarray):        # a bare trajectory is a 1-scene task
            scenes = [scenes]
        self.scenes = tuple(np.asarray(s) for s in scenes)
        if not self.scenes:
            raise ValueError('a task needs at least one scene')
        shapes = {s.shape[1:] for s in self.scenes}
        if len(shapes) != 1:
            raise ValueError(f'scenes disagree on grid shape: {shapes}')

    # ── identity ─────────────────────────────────────────────────────────────
    @property
    def key(self):
        "Hashable, picklable task identity: every scene, in order."
        return tuple((s.shape, s.tobytes()) for s in self.scenes)

    @property
    def id(self):
        "Stable hex id — the JSON-serialisable form of `key` (same scenes → same id)."
        h = hashlib.sha1()
        for s in self.scenes:
            h.update(repr(s.shape).encode())
            h.update(s.tobytes())
        return h.hexdigest()

    def __hash__(self):
        return hash(self.key)

    def __eq__(self, other):
        return isinstance(other, Scenes) and self.key == other.key

    # ── access ───────────────────────────────────────────────────────────────
    def __len__(self):
        return len(self.scenes)

    def __iter__(self):
        return iter(self.scenes)

    @property
    def k(self):
        return len(self.scenes)

    @property
    def rep(self):
        """A representative scene, for anything that needs ONE trajectory: task
        figures, the recognition model's grid encoder, sample export.  Never use
        it to decide whether a program solves the task — that is `solves`."""
        return self.scenes[0]

    @property
    def grids(self):
        "The k initial grids."
        return [s[0] for s in self.scenes]

    @property
    def values(self):
        "Every entity value the task's initial grids mention (0 = empty, 3 = wall excluded)."
        return {int(v) for s in self.scenes for v in np.unique(s[0]) if v not in (0, 3)}

    def __repr__(self):
        return f'Scenes(k={self.k}, T={[int(s.shape[0]) for s in self.scenes]})'


def as_scenes(x):
    "Accept either a Scenes or a bare trajectory; always return a Scenes."
    return x if isinstance(x, Scenes) else Scenes(x)


# ── solving ──────────────────────────────────────────────────────────────────

def run(prog, scene, template=None):
    """Apply a per-frame fn (or a pair-commit, when `template` is given) to a
    scene's initial grid for that scene's own T.  Returns None if it throws or
    degenerates, so callers can compare without guarding every call."""
    import dsl as _dsl
    try:
        out = (_dsl.unfold_with_template(scene[0], template, scene.shape[0], prog)
               if template is not None else
               _dsl.unfold(scene[0], scene.shape[0], prog))
    except Exception:
        return None
    if not isinstance(out, np.ndarray) or 0 in out.shape:
        return None
    return out


def solves(prog, task, templates=None):
    """True iff `prog` reproduces EVERY scene of the task.

    This is the whole point of the multi-scene format, so it is the only place
    allowed to decide it.  Short-circuits on the first mismatch: almost every
    enumerated program dies on scene 1, so k scenes cost ~1 unfold on average,
    not k.
    """
    task = as_scenes(task)
    for i, scene in enumerate(task):
        out = run(prog, scene, templates[i] if templates is not None else None)
        if out is None or not np.array_equal(out, scene):
            return False
    return True


def solves_any(prog, task, templates=None):
    "True iff `prog` reproduces at least one scene — for 'this latent is inert here' checks."
    task = as_scenes(task)
    for i, scene in enumerate(task):
        out = run(prog, scene, templates[i] if templates is not None else None)
        if out is not None and np.array_equal(out, scene):
            return True
    return False
