#import "lib.typ": *

#mol-chapter("Chapter 0")

== Section

Our sensory organs receive a continuous stream of raw unstructured data. The photons hitting your retina don't mean anything, don't represent anything, don't contain information. To make use of this data we need to cognize it, to conceptualize it. We digitize the data: we compress it into symbols that represent facts about the world, facts that have informational content. We create a model of the world, an abstract structure that represents relevant information. Within this model, we can run deductive/inductive inference to develop a promising plan of action that we can execute in the real world. 

== Hypothesis

I use "concept", "primitive", "function", and "operation" interchangably. I'll say that primitives like _believes_, _intends_, _desires_, _agent_, _goal_ etc. are "mental" primitives, whereas _moves_, _approaches_, etc are "physical" primitives. I'll say "mental theory" for an explanation of data where some of its constituent concepts are mental. I use "theory", "explanation", "(world) model", "program", and "hypothesis" interchangably. For example, say the data is a scene of a dog walking along a dog park with a ball in its mouth. "The dog wants to keep the ball and make sure that other dogs don't take it away so it clenches its jaws around it" is a mental theory. "The ball is lodged in the dog's mouth, stuck between its jaws" is a physical theory. My hypothesis is that, in principle, mental primitives need not be innately endowed. Rather, they can be learned from data and from non-mental primitives.

I suspect this because mental theories are often the simplest most parsimonious explanations for data, because they're often the correct explanation. It's much easier to explain a person's behavior by positing that they're an agent who has goals they act upon, than to give a full physicalist explanation of every component of what they do. The latter is possible, but it's far more verbose. Say a system emumerates candidate hypotheses, evaluates them in order from least to most likely, from most to least complicated and verbose. Then such a system will have a preference for mental explanations over physical, when the data actually involves rational agents. A (good) model is an isomorphism of the world, it has analigous components that are in the same relation as those in the real world. A model is a representation of the world, an explanation of what the underlying mechanisms are that produced the data. 

Theory of mind is a domain of reasoning, just like physical reasoning. The intuition is that learning how to theorize about minds shouldn't be fundamentally different than learning how to theorize about any other domain. It's just a different domain. If the framework of enumerating and evaluating theories to find the best and simplest one is the same across domains, then there's nothing special about mind. I feel like people get carried away with mind, they think there's something inherently special about seeing things as rational agents, that there's something profound about it, that we're innately like this. And it can seem that way, because it's so intuitive for us to see things that way. But that need not be because it's innate. I content that it's intuitive just because it's useful, because we're surrounded by intentional agents, so we quickly learn that to see them that way is the most helpful and succinct theory for understanding them.

To emphasize: the frawework of theory testing is the same, domain-general. What changes are the domain-specific components, the operations that are composed to build theories. Hypotheses are programs written in a vocabulary of concepts. They are written in a language of thought, which is written compositionally. So as I see it, learning to reason in a particular domain means learning the concepts "of" that domain. The reasoning itself is the same. So learning to do mental reasoning is just learning the concepts "believes", "wants", etc. It's learning a DSL. I use "domain-specific lanugage" and "(conceptual) vocabulary" interchangably. 

So how do we learn a concept? What does it mean to learn a concept? In this model, concepts themselves are compositional. A hypothesis is composed of concepts, and a concept is composed of smaller concepts. So a concept is an abstraction. It's shorthand for referring to a more complicated composition of smaller operations, so that those same operations can be referred to more efficiently. For example, I could explain all the rules of baseball or I could just call it "baseball", which is an abstraction that simplifies the reference. So we start out with some hard-coded primitive operations in the DSL, and then as we discover similar structures in succesful programs, we abstract those structures and add them to the DSL as new concepts. Then the next time we randomly enumerate candidate programs, we're more likely to generate programs that have that useful structure already, rather than needing to reinvent the wheel every time. 

pattern recognition, compression, digitizing the analogue data

So there are primitives. We need to start from somewhere. But the idea is that we only need to start from fairly low-level primitives, from primitives that don't encode any mental notions. Also, disambiguation: I use "primitives" in the general sense to mean concepts in the DSL, but in the context of adding new concepts to the DSL, I refer to the original ones as the primitives. So the new ones are "constructed primitives" or "learned primitives" or something.

As an example, rather than going from movement to mental, say we go from object recognition to movement. We start with a bunch of primitives for objects, and then we learn persistence, and then eventually learn movement. There's nothing physical in the original DSL, but we've learned to have movement primitives still. Similarly, this is a leap that can happen from movement to mental. 

A good program correctly generates the data. The data in the real world was generated by some unknown underlying process. Our goal is to try to get as close as possible to figuring out what that process is. So if we find a program that precisely generates the same data as in the world, then it's a good model because it's probably pretty similar to the real-world process. 

Clarification: in the context of my thesis, "theory"/"hypothesis"/"model" mean the individual instances of explanations themselves, as posited by a person/system. 

but I also sometimes use them in the meta sense, like
- "my hypothesis" that mental primitives can be learned
- or "my model" which is the simplified version of cognition that I'm working with, an analogy, an implementation in which we can test things out (when I talk about the literal implementation itself I try to call it "the system" so it's distinguished from "program", which is what the system generates)
- or the "theory theory" which is a theory in cognitive science, that children posit theories about the world, that children are like scientists looking for the best theory to explain the data (which is what I'm working with here). 

