#import "@preview/illc-mol-thesis:0.2.0": *

#mol-chapter("Theory of Mind and its Acquisition")

== The Nature and Scope of Theory of Mind

The ice cream peddler's scratchy jingle got louder still as he brought his cart to a stop nearby. A child, hitherto engrossed in sandbox amusements, abandoned her playmates abruptly. She darted across the playground, hurtling at full speed towards a gaggle of parents. Absorbing the impact of a 20 kg cruise missile, the target continued his conversation unfazed by the girl now tugging at his jeans. Only when he deigned to look down at the child did he shriek and go pale. But the girl barely had time to react, because just then she heard her name shouted from the other side of the playground. She turned to its source and ran towards a similar-looking man whose outstretched arms held two ice cream cones.

You chuckle at the scene, observing from a nearby park bench. The girl, wanting ice cream, pestered a man she thought was her father. The man, undoubtedly accustomed to his own nagging kids, ignored the girl thinking it was his own child. Descriptions like these, in terms of desires, beliefs, and intentions, seem trivial and obvious. But there's something miraculous about them. How are you able to peer into other peoples' minds? Mental content is unobservable; all you see is a sequence of physical actions. And yet humans, even infants, are experts at inferring mental content rapidly and accurately.

Humans have the cognitive ability to impute mental states to others: to attribute a belief, a desire, or an intention to another person. This capacity is known as "theory of mind", "commonsense psychology", "naive psychology", "folk psychology", or the ability to "mindread", to "mentalize" @margolis_oxford_2012. Among these we'll primarily use "theory of mind", henceforth ToM @premack_does_1978. We choose this term to emphasize that this capacity is a _theory_ proper in that it enables behavioral prediction by positing states that are not directly observable @gopnik_why_1992. 

// TODO: intenti0onal stance, Dennet. The capacity for ToM is integral to our humanity: to cooperate with someone you have to understand what they think and what they want, to decode someone's words you have to begin from what they are trying to do with them. Humans make these inferences so naturally that the capacity can look like no achievement at all. We eagerly construe and the disposition does not even wait for a plausible target --- a fact @sec-planner returns to when it takes up Dennett's intentional stance.

The mental states we attribute include perceptual states, bodily feelings, emotional states, and propositional attitudes such as beliefs, desires, hopes and intentions @margolis_oxford_2012. This thesis is concerned with the attribution of propositional attitudes, particularly belief. A propositional attitude relates an agent to some content ("she believes that _x_"), so to attribute a belief to an agent is to attribute a _model_ that may diverge from the world, and to predict behaviour from the model rather than from the world @crane_mechanical_nodate @perner_understanding_1991. In this thesis we study how this capacity to attribute and predict off a divergent world model is acquired. How do humans, even at a young age, come to have it?

== Experimental Evidence: Developmental Milestones <timeline>

ToM doesn't arrive all at once, but in pieces over roughly four years and in a roughly fixed order @wellman_scaling_2004@coskun_new_2020 @beaudoin_systematic_2020 @wellman_theory_2018 @rakoczy_foundations_2022. Long before children can say anything about minds, they parse motion as goal-directed. Woodward habituated 5- to 9-month-olds to a hand reaching for one of two objects and then swapped the objects' positions. Infants looked longer when the hand reached to the old location for a new object than when it reached to a new location for the old object @woodward_infants_1998. So the infant encodes the goal object, not the trajectory.

Gergely et al. showed that, more than object-directed, the interpretation is even efficiency-sensitive: 12-month-olds expect an agent to take the most efficient means its situation affords, and are surprised when it does not @gergely_taking_1995. Gergely and Csibra call this schema the _teleological stance_ and distinguish it from the intentional stance @gergely_teleological_2003 @csibra_obsessed_2007 So before the first birthday, an infant can read bodies as taking efficient means to ends. This is _not_ ToM. There's no attribution of mental states, it's just an extensional story.

In the second year, infants become sensitive to what an agent can (and can't) see, and begin to condition their expectations about an agent's goal based on the agent's perceptual access to the objects involved @luo_toward_2010. This is a perspective-taking ability, but restricted mostly to the epistemic case of perceptual access. ToM similarly requires perspective-taking, but pertaining to more complex mental states. 

//The transition that has organized the field is the one from reality-centred to belief-centred prediction.

The jump to ToM involves a transition from reality-centered to belief-centered prediction. In the original _false-belief_ task, Maxi puts his chocolate in one cupboard and leaves; his mother moves it to another; Maxi returns, and the child is asked where he will look @wimmer_beliefsabout_nodate.#footnote[The task is also commonly known as the Sally--Anne task @baron-cohen_does_1985, with similar setup] Though the observing child knows the chocolate is in the other cupboard, the child must predict Maxi's behavior according to _his_ (false) belief, not according to the _child's_ (true) belief. Children under about 3.5 years consistently fail, and (tellingly) their scores don't improve when the scenario is made more explicit. The age threshold is robust across task variations, countries and manipulations, aggregated over 178 studies @wellman_meta-analysis_2001.#footnote[4 years as the threshold has been challenged by studies seemingly showing _implicit_ false-belief ability around 1.5 years @onishi_15-month-old_2005 @southgate_action_2007 @buttelmann_eighteen-month-old_2009. But the findings have replicated badly @kulke_is_2018 @dorrenberg_how_2018 @barone_infants_2019 and even granting them, they may be accounted for by early automatic tracking abilities @apperly_humans_2009 @butterfill_how_2013. For the purposes of this thesis, we take the ToM scale @wellman_meta-analysis_2001 @wellman_scaling_2004 as our explanandum.]

//Perner's account of what changes is that the child comes to understand the mind as a _representational_ device, one whose states can misrepresent @perner_understanding_1991. In later age (4- to 5) children come to embed the "believes" operator in itself, asking not what John believes but what John believes _Mary_ believes @perner_john_1985. So the belief operator can be applied to its own output.

== The Explanandum <explanandum>

We first state some of the features of the ToM capacity, which a (good) theory of the acquisition of ToM must account for. Take for example someone trying to learn an intuitive physics by watching a ball's motion. The learner can simply extract regularities from what she sees, because a ball's position and velocity are recoverable from a sequence of images. A learner of intuitive psychology (ToM) doesn't have that luxury. What is available to the observer is a trajectory of bodies through space, but what has to be acquired is a vocabulary of attitudes that appear nowhere in the trajectory @polivy_empiricism_nodate @churchland_eliminative_1981. So an acquisition procedure which works by finding structure in the observable variables can't yield ToM. 

Another acquisition problem is that attributions are underdetermined by behaviour.#footnote[For example, an agent walking across the room to the cupboard can be explained as wanting the chocolate and believing it is there, or as wanting to check whether it has been moved and believing it is there, or as wanting to be seen approaching the cupboard, and so on without end.] Any behaviour is compatible with indefinitely many belief--desire pairs and no amount of further observation narrows the field to one, similarly to Quine on translation @quine_word_2013.#footnote[This is a special case of the fact that data does not select a hypothesis without a prior @goodman_fact_1983.] Yet humans select a fitting belief--desire explanation quickly, confidently, and on very little data. An acquisition theory should explain what does the selecting. 

The underdetermination problem presupposes a learner who already has the concepts and must choose among ascriptions built from them. But a learner who lacks the concept _believes_ cannot make even a wrong attribution. So the acquisition problem isn't just curve-fitting or parameter estimation within a given theory. It requires constructing the theory's terms, positing unobservable entities to explain observable behavior. Fodor argued that no learning process could deliver a concept the learner did not in some sense already have @fodor_concepts_1998 @fodor_theory_1992, and Carey's work on conceptual change tries to answer Fodor's challenge @carey_origin_2011. An account of acquisition must explain how novel conceptual terms can come to exist.

Because _believes_ takes any proposition as an argument, the set of available attributions is unbounded: one can entertain attributions never encountered in the data, including attributions of beliefs one takes to be false and beliefs about things that do not exist. The operator also embeds in itself, which enables second-order mentalizing @perner_john_1985. And the attributions come in systematic families: anyone who can represent that Sally believes the marble is in the basket can also represent that Anne believes it is in the box @fodor_connectionism_nodate. The terms get their content from their role in a network of inferences rather than from links to observations one at a time. So a good acquisition theory must offer a representational medium in which mental content composes, embeds, and licenses inference.

Finally, we saw in @timeline that goal attribution is in place before the first birthday while explicit false-belief prediction is not reliable until around four. A good account of ToM acquisition should explain this long delay. Also, the later competences look like assemblies of the earlier ones: belief attribution appears to be goal attribution plus subjective perceptual access. So in a good account, this ordering would be a explained by the acquisition mechanism itself. 

== Theoretical perspectives on ToM acquisition <perspectives>

We now survey the standing accounts of how theory of mind is acquired, evaluating them according to the ToM features in @explanandum. Nativism, empiricism, and constructivism are general positions in the debate about cognitive development, but we'll consider them specifically in the ToM context.#footnote[There's also simulationism, which denies that mindreading proceeds by a theory at all. On this account the attributor runs her own decision-making machinery offline on pretend inputs rather than applying general principles connecting states to behaviour @gordon_folk_1986 @goldman_simulating_2006.] 

=== Nativism and core knowledge <nativism>

The nativist holds that ToM is a built-in system that matures over time, so it's not acquired from data in any interesting sense. Nativist positions are mainly motivated by the poverty of stimulus argument (PoS): the data available to the child is too sparse and too degenerate to fix the target by general learning, so the constraints that do fix it must be innate and domain-specific @chomsky_aspects_2014 @chomsky_reflections_1975 @berwick_poverty_2011. 

Leslie argues for a theory of mind module (ToMM): a natively endowed, domain-specific system for interpreting the behaviour of intentional agents, which introduces attitude concepts such as _believes_ and deploys a "proprietary representational system" for ascribing them to agents @leslie_pretense_nodate @leslie_pretending_1994. The dissociation found in autism is held as evidence that ToM is a dedicated system, since it can be selectively impaired @baron-cohen_does_1985 #footnote[TODO though these experiments have also faced replication troubles ADD CITATIONS].

Fodor's nativism argues that the child's theory of mind is not learned, because there is no coherent story on which a concept like belief could be learned @fodor_theory_1992. So concepts are not constructed, and the productivity and systematicity of ToM are properties of a representational format that was there from the start. There's also the "core knowledge" nativist position, which posits a small stock of encapsulated systems that give the child a skeletal domain-specific ontology from which they elaborate to more complex concepts @spelke_core_2007 @spelke_what_2022.

The almost three year developmental delay from goal attribition to false-belief prediction is a challenge for nativists, since they must explain why an innate capacity isn't manifested until later in development. A ToMM account can appeal to maturation of the module, or argue that task performance demands mask underlying native competence @leslie_developmental_2005 @scholl_minds_2001. But these concessions accomodate the developmental data by auxiliary hypotheses. What would be better is a theory that itself predicts staggered developmental results. 

Nativism answers the hard requirement --- how a learner comes to have terms for unobservables --- by declining it. 

// the manoeuvre means the developmental data is being accommodated by auxiliary hypotheses rather than predicted by the theory. That weakens the position considerably given that the developmental data is the main thing to be explained.

// and given the implicit false-belief findings of @timeline this may well be right --- those findings are, on any reading, the best evidence the nativist has, and it is no accident that the two-systems response to them concedes an early automatic tracker @apperly_humans_2009. But two things follow. First, the replication record means the concession cannot be leaned on heavily @kulke_is_2018 @barone_infants_2019. Second, and more importantly, 

=== Empiricism, association, and cultural learning <empiricism>

The empiricist holds that theory of mind is learned like anything else: through experience, from statistical regularities, by bottom-up association. In a connectionist implementation knowledge is distributed over the weights of a network, concepts are patterns of activation rather than symbols, and structure in behaviour is emergent rather than represented @rumelhart_parallel_1986 @mcclelland_emergence_2010. Connectionist networks have even been shown to account for false belief without using symbolic representation @berthiaume_constructivist_2013.

There's also Heyes' non-connectionist position which takes that ToM is a cognitive gadget, i.e. a culturally inherited skill assembled out of general-purpose learning mechanisms and transmitted through social interaction and talk about the mind (rather than a genetically inherited instinct) @heyes_cultural_2014 @heyes_cognitive_2018. Ruffman argues in a similar spirit that the developmental data can be accounted for without crediting children with belief concepts at all, by low-level and statistical means @ruffman_belief_2014. In the linguistic domain, one empiricist approach derives the capacity to represent a false complement from acquiring the syntax of sentential complementation @de_villiers_can_nodate @milligan_language_2007.

Empiricist accounts are well-suited to explaining how ToM emerges even though mental content isn't in the data. But these explanations often deny that the structure of ToM is acquired at all, instead they just show how the learner acquires useful associations from data: it learns a mapping. And then the empiricist can't account for systematicity, since there's no representational medium with constituent structure @fodor_connectionism_nodate. 

Against a purely associative empiricism, the observed developmental order (@timeline) is not obviously the order of frequency in experience. Nothing about the input makes goal-directed pursuit a hundredfold more frequent than the conjunction of pursuit with restricted perceptual access. And no empiricist implementation shows how a data frequency difference leads to a three year false belief delay.

Furthermore, the later competences appear to presuppose the earlier ones rather than to be acquired independently alongside them as a separate regularity learned from its own statistics. The cultural-learning empiricist could attribute the competency ordering to the ordering of the input @heyes_cultural_2014. But that's a hypothesis about the input rather than a mechanism, and also it predicts that the developmental sequence should vary between children more than it appears to @wellman_scaling_2004.

Empiricism takes seriously the fact that the content is not in the data, and then concludes that there is no content to acquire.

=== Rational constructivism and the theory theory <constructivism>

The constructivist holds that the child is analogous to a scientist @gopnik_scientific_2012 @downes_can_1999. A child constructs intuitive theories of mind and world which she revises in light of evidence, by something like the process that drives scientific progress @gopnik_why_1992 @gopnik_words_1997 @wellman_childs_1990. So domain-general statistical machinery constructs domain-specific structured knowledge. Infants have been shown to be sensitive to sampling and to statistical evidence in ways that indicate they do inference to hidden structure (including psychological structure) @xu_infants_2013 @wellman_infants_2016 @xu_towards_2019. And in general children's exploratory behaviour is well described as evidence-gathering aimed at resolving uncertainty about which theory is right @schulz_origins_2012.



Rational constructivists specify that Bayesian inference is the formal mechanism of theory change @gopnik_reconstructing_2012 @newcombe_what_2011 @xu_rational_2012. Structured, abstract knowledge, embedded in a probabilistic framework, can be acquired from sparse and noisy data @gopnik_bayesian_2007 @griffiths_probabilistic_2010 @perfors_variability_2010 @griffiths_bayes_2011 @xu_towards_2019 @ullman_bayesian_nodate. For example, the transition from failure to success in false-belief tasks is analyzed as an evidence-driven shift between two causal Bayesian models. The infant starts with a simpler model, but after encountering evidence inexplainable by that model switches to a more complex one which offers greater explanatory resources @goodman_intuitive_nodate.

Theory formation generally has been modeled as probabilistic inference over systems of related concepts @kemp_probabilistic_2010 @goodman_learning_2011, and theory change has been modelled as stochastic search through a space of theories generated by a grammar @ullman_theory_nodate. 

Theories have terms; theory change introduces new ones; and the terms are answerable to evidence without being read off it.



Nativism posits domain-specific logical symbolic mechanisms, whereas empiricism posits domain-general probabilistic statistical mechanisms. Rational constructivism seeks a middle-way between various dichotomies in the field @griffiths_bayesian_2024

"Powerful abstractions can be learned surprisingly quickly, together with or prior to learning the more concrete knowledge they constrain. Structured symbolic representations need not be rigid, static, hard-wired, or brittle. Embedded in a probabilistic framework, they can grow dynamically and robustly in response to the sparse, noisy data of experience." @tenenbaum_how_2011


, by asking "how can domain-general mechanisms of learning and representation build domain-specific systems of knowledge? How can structured symbolic knowledge be acquired through statistical learning?" @tenenbaum_how_2011 



"How do our minds get so much from so little?" @griffiths_bayesian_2024 poverty of stimulus

On this account the four-year transition is a theory change. The child's earlier answers are systematic and wrong (rather than merely absent) because she has an earlier theory. 

*The delay.* This is the position that says the most about the ordering, because it says that acquisition is _cumulative_: what is learned early becomes the material out of which what is learned later is composed. That is the bootstrapping picture @carey_origin_2011 @piantadosi_bootstrapping_2012. The explanandum is then not merely that the capacity appears but that it appears in this order, with the later stages built from the earlier ones, and the account has the right shape to explain it. A prior over hypotheses is a way of selecting among attributions that the data underdetermines; a structured representational medium is one in which content composes, embeds, and executes; and a mechanism by which abstractions acquired early become the primitives from which later ones are built is exactly what a cumulative ordering requires. Whether such a mechanism actually delivers a mental vocabulary, rather than merely being able to express one, is the question the rest of this thesis puts to the test.

The theory theory comes closest. It has the right shape for every one of the five requirements: theories have terms, terms are constructed, construction is answerable to evidence, the medium is structured, and construction is cumulative so the order of acquisition is a consequence of what has already been built. But having the right shape is not the same as being a mechanism. The account says that children construct theories; it does not say what process does the constructing, nor by what standard one candidate theory is preferred to another, nor --- and this is the sharp version --- how a learner searches a space of possible theories that is infinite. The metaphor of the child as scientist is powerful, and it describes what happens rather than naming something that would make it happen.

That gap is what keeps the nativist in business. Absent a mechanism, the nativist can say that no constructive process exists, that what looks like construction is really the maturation of something already in place, and that the appearance of theory change is a redescription of a developmental timetable. The strength of that reply is parasitic on the absence of a mechanism. It is not an argument that construction is impossible; it is an argument that nobody has exhibited one.

So the business of the next chapter is to supply one. If the theory theory needs a process that searches a space of structured hypotheses, prefers among those that fit the data on principled grounds, introduces new terms whose content is fixed by their role rather than by observation, and makes what is learnable at each stage depend on what has already been learned, then that is a specification, and it is a specification we can go looking for a formal system to meet. Chapter 2 argues that Bayesian program induction is such a system, and that DreamCoder is a concrete algorithm that implements it.

#load-bib(read("refs.bib"))
