#import "lib.typ": *

#mol-chapter("Theory of Mind and its Acquisition", lbl: <ch-tom>)

== The nature and scope of Theory of Mind

The ice cream peddler's scratchy jingle got louder still as he brought his cart to a stop nearby. A child, hitherto engrossed in sandbox amusements, abandoned her playmates abruptly. She darted across the playground, hurtling at full speed towards a gaggle of parents. Absorbing the impact of a 20 kg cruise missile, the target continued his conversation unfazed by the girl now tugging at his jeans. Only when he deigned to look down at the child did he shriek and go pale. But the girl barely had time to react, because just then she heard her name shouted from the other side of the playground. She turned to its source and ran towards a similar-looking man whose outstretched arms held two ice cream cones.

You chuckle at the scene, observing from a nearby park bench. The girl, wanting ice cream, pestered a man she thought was her father. The man, undoubtedly accustomed to his own nagging kids, ignored the girl thinking it was his own child. Descriptions like these, in terms of desires, beliefs, and intentions, seem trivial and obvious. But there's something miraculous about them. How are you able to peer into other peoples' minds? Mental content is unobservable; all you see is a sequence of physical actions. And yet humans, even infants, are experts at inferring mental content rapidly and accurately.

Humans have the cognitive ability to impute mental states to others: to attribute a belief, a desire, or an intention to another person. This is the capacity for "theory of mind" (ToM), also known as "commonsense psychology", "naive psychology", "folk psychology", "mindreading", "mentalizing" @margolis_oxford_2012. We'll primarily use the term Theory of Mind (ToM), to emphasize that this capacity is a _theory_ proper in that it enables behavioral prediction by positing states that are not directly observable @gopnik_why_1992. 

The capacity for ToM is integral to our humanity: to cooperate with someone you have to understand what they think and what they want, to decode someone's words you have to begin from what they are trying to do with them. Humans make these inferences so naturally that the capacity can look like no achievement at all. We eagerly take the intentional stance towards entities in our environment @dennett_intentional_2002 and attribute mental states to them. 

The mental states we attribute include perceptual states, bodily feelings, emotional states, and propositional attitudes such as beliefs, desires, hopes and intentions @margolis_oxford_2012. This thesis is concerned with the attribution of propositional attitudes, particularly belief. A propositional attitude relates an agent to some content ("she believes that _m_"). So to attribute a belief to an agent is to attribute to her a model $m$ of the world $w$ (where $m$ may differ from $w$), and then to predict that she will behave according to her own private model $m$ rather than according to the actual world $w$ @crane_mechanical_2015 @perner_understanding_1991. In this thesis we study how the _structure_ of this attribution function might be acquired. How do humans, even at a young age, come to have this ability?

== Experimental Evidence: Developmental Milestones <timeline>

ToM doesn't arrive all at once, but in pieces over roughly four years and in a roughly fixed order @wellman_scaling_2004@coskun_new_2020 @beaudoin_systematic_2020 @wellman_theory_2018 @rakoczy_foundations_2022. Long before children can say anything about minds, they parse motion as goal-directed. Woodward habituated 5- to 9-month-olds to a hand reaching for one of two objects and then swapped the objects' positions. Infants looked longer when the hand reached to the old location for a new object than when it reached to a new location for the old object @woodward_infants_1998. So the infant encodes the goal object, not the trajectory.

Gergely et al. showed that, more than object-directed, the interpretation is even efficiency-sensitive: 12-month-olds expect an agent to take the most efficient means its situation affords, and are surprised when it does not @gergely_taking_1995. Gergely and Csibra call this schema the _teleological stance_ and distinguish it from Dennett's intentional stance @gergely_teleological_2003 @csibra_obsessed_2007 So before the first birthday, an infant can read bodies as taking efficient means to ends. This is _not_ ToM. There's no attribution of mental states, it's just an extensional story.

// In the second year, infants become sensitive to what an agent can (and can't) see, and begin to condition their expectations about an agent's goal based on the agent's perceptual access to the objects involved @luo_toward_2010. This is a perspective-taking ability, but restricted mostly to the epistemic case of perceptual access. ToM similarly requires perspective-taking, but pertaining to more complex mental states. 

The jump to ToM involves a transition from reality-centered to belief-centered prediction. In the _false-belief_ task, a child watches Sally put her marble in a basket and leaves. While Sally's away, Anne moves the marble to the box. When Sally returns, the experimenter asks the child to predict where Sally will look for the marble @baron-cohen_does_1985 @wimmer_beliefs_1983. Though the observing child knows the marble is actually in the box, the child must predict Sally's behavior according to _her_ (false) belief, not according to the _child's_ (true) belief. Children under about 3.5 years consistently fail, and (tellingly) their scores don't improve when the scenario is made more explicit.

The 3.5-year age threshold is robust across task variations, countries and manipulations, aggregated over 178 studies @wellman_meta-analysis_2001. However it's been challenged by studies seemingly showing implicit false-belief ability around 1.5 years @onishi_15-month-old_2005 @southgate_action_2007 @buttelmann_eighteen-month-old_2009. But the findings have replicated badly @kulke_is_2018 @dorrenberg_how_2018 @barone_infants_2019 and even granting them, they might be accounted for by early automatic tracking abilities @apperly_humans_2009 @butterfill_how_2013. For the purposes of this thesis, we take the ToM scale @wellman_meta-analysis_2001 @wellman_scaling_2004 as our explanandum, which demonstrates that children perform progressively better on more complex ToM tasks as they mature. 

//Perner's account of what changes is that the child comes to understand the mind as a _representational_ device, one whose states can misrepresent @perner_understanding_1991. In later age (4- to 5) children come to embed the "believes" operator in itself, asking not what John believes but what John believes _Mary_ believes @perner_john_1985. So the belief operator can be applied to its own output.

== What a good account of ToM acquisition ought to explain <explanandum>

We seek an explanation for how ToM is acquired. To evaluate competing theories, we'll set out some of the features of ToM that must be explained by an adequate account of its acquisition.

For one, mental content isn't in the data. Take for example someone trying to learn an intuitive physics by watching a ball's motion. The learner can simply extract regularities from what she sees, because a ball's position and velocity are recoverable from a sequence of images. A learner of ToM (intuitive psychology) doesn't have that luxury. What is available to the observer is a trajectory of bodies through space, but what has to be acquired is a vocabulary of attitudes that appear nowhere in the trajectory @polivy_empiricism_nodate @churchland_eliminative_1981. So an acquisition procedure which works by finding structure in the observable variables can't yield ToM. 

Not being in the data, attributions are severely underdetermined by behavior. An agent walking across the room to the cupboard can be explained as wanting the chocolate and believing it is there, or as wanting to check whether it has been moved and believing it is there, or as wanting to be seen approaching the cupboard, and so on without end. Any behaviour is compatible with indefinitely many belief--desire pairs and no amount of further observation narrows the field to one, similarly to Quine on translation @quine_word_2013.#footnote[This is a special case of the fact that data does not select a hypothesis without a prior @goodman_fact_1983.] Yet humans select a fitting belief--desire explanation quickly, confidently, and on very little data. An acquisition theory should explain what does the selecting. 

The underdetermination problem presupposes a learner who already has the concepts and must choose among ascriptions built from them. But a learner who lacks the concept _believes_ cannot make even a wrong attribution. So the acquisition problem isn't just curve-fitting or parameter estimation within a given theory. It requires constructing the theory's terms, positing unobservable entities to explain observable behavior. Fodor argued that no learning process could deliver a concept the learner did not in some sense already have @fodor_concepts_1998 @fodor_theory_1992, and Carey's work on conceptual change tries to answer Fodor's challenge @carey_origin_2011. An account of acquisition must admit novel conceptual terms and explain how they come to exist.

And these terms should compose and embed. Since "believes" takes any proposition as an argument, the set of available attributions is unbounded: one can entertain attributions never encountered in the data, including attributions of beliefs one takes to be false and beliefs about things that do not exist. The operator also embeds in itself, which enables second-order mentalizing @perner_john_1985. And the attributions are systematic: anyone who can represent that Sally believes the marble is in the basket can also represent that Anne believes it is in the box @fodor_connectionism_1988. The terms get their content from their role in a network of inferences rather than from links to observations one at a time. So a good acquisition theory must offer a representational medium in which mental content composes, embeds, and licenses inference.

Finally, we saw in @timeline that goal attribution is in place before the first birthday while explicit false-belief prediction is not reliable until around four. A good account of ToM acquisition should explain this long delay. Also, the later competences look like assemblies of the earlier ones: belief attribution appears to be goal attribution plus subjective perceptual access. So in a good account, this ordering would be a explained by the acquisition mechanism itself. 

== Theoretical perspectives on ToM acquisition <perspectives>

We now survey the standing accounts of how theory of mind is acquired and evaluate them according to the ToM features (@explanandum). Nativism, empiricism, and constructivism are general positions in the debate about cognitive development, which we'll consider specifically in the ToM context, while simulationism is specific to ToM. 

=== Nativism and core knowledge <nativism>

The nativist holds that ToM is a built-in system that matures over time, so it's not acquired from data in any interesting sense. Nativist positions are mainly motivated by the poverty of stimulus argument (PoS): the data available to the child is too sparse and too degenerate to fix the target by general learning, so the constraints that do fix it must be innate and domain-specific @chomsky_aspects_2014 @chomsky_reflections_1975 @berwick_poverty_2011. Rather than answer the difficult question of how a learner comes to have terms for unobservables, the nativist denies the premise that these terms are learned. 

Leslie argues for a theory of mind module (ToMM): a natively endowed, domain-specific system for interpreting the behaviour of intentional agents, which introduces attitude concepts such as _believes_ and deploys a "proprietary representational system" for ascribing them to agents @leslie_pretense_1987 @leslie_pretending_1994. Autism studies are held as evidence that ToM is a dedicated system, since they seemingly show it can be selectively impaired @baron-cohen_does_1985. Fodor argues that the child's theory of mind is not learned, because there is no coherent story on which a concept like belief could be learned @fodor_theory_1992, so the productivity and systematicity of ToM are properties of a representational format that was there from the start. There's also the "core knowledge" position, which posits a small stock of encapsulated systems that give the child a skeletal domain-specific ontology from which they elaborate to more complex concepts @spelke_core_2007 @spelke_what_2022.

The almost three year developmental delay from goal attribition to false-belief prediction is a challenge for nativists, since they must explain why an innate capacity isn't manifested until later in development. A ToMM account can appeal to maturation of the module, or argue that task performance demands mask underlying native competence @leslie_developmental_2005 @scholl_minds_2001. But these concessions accomodate the developmental data by auxiliary hypotheses. What would be better is a theory that itself predicts staggered developmental results.

And the early findings don't show as much as they are taken to. Nativists often point to studies showing even young infants have abstract domain knowledge @wellman_cognitive_1992 as  evidence for innateness. But such evidence doesn't by itself favor nativism, since the infant could just as well have acquired it (early) through learning rather than having it innately. 

=== Empiricism, association, and cultural learning <empiricism>

The empiricist holds that theory of mind is learned like anything else: through experience, from statistical regularities, by bottom-up association. But what's learned isn't the structure of ToM, like attitude concepts or a domain-specific representational system (the nativist would just bring up PoS, that there's not enough data to learn that structure). For the empiricist, that structure is just how researchers model ToM at a high level.

In a connectionist implementation knowledge of ToM is distributed over the weights of a network. So concepts are patterns of activation rather than symbols, and structure in behaviour is emergent, it's not represented explicitly in the system @rumelhart_parallel_1986 @mcclelland_emergence_2010. Connectionist networks have even been shown to account for false belief without using symbolic representation @berthiaume_constructivist_2013. 

There's also Heyes' non-connectionist position which takes that ToM is a cognitive gadget, i.e. a culturally inherited skill assembled out of general-purpose learning mechanisms and transmitted through social interaction and talk about the mind (rather than a genetically inherited instinct) @heyes_cultural_2014 @heyes_cognitive_2018. Ruffman argues in a similar spirit that the developmental data can be accounted for without crediting children with belief concepts at all, by low-level and statistical means @ruffman_belief_2014.

Empiricist accounts are well-suited to explaining how ToM emerges even though mental content isn't in the data. But these explanations often deny that the structure of ToM is acquired at all, instead they just show how the learner acquires useful associations from data: it learns a mapping. And then the empiricist can't account for systematicity, since there's no representational medium with constituent structure @fodor_connectionism_1988.

An empiricist theory would predict that development of competencies scales with frequency of exposure to that data, but that doesn't explain the developmental order (@timeline). No empiricist implementation shows how a data frequency difference leads to a two year false belief delay. Also, the later competences appear to presuppose the earlier ones rather than to be acquired alongside them as separate regularities learned from their own statistics. The cultural-learning empiricist could attribute the competency ordering to the ordering of the input @heyes_cultural_2014, but that's a hypothesis about the input rather than a mechanism, and it predicts that the developmental sequence should vary between children more than it appears to @wellman_scaling_2004.

=== Simulationism <simulationism>

Simulationism is different than all the other positions because it doesn't see ToM as a body of knowledge that needs to come from somewhere, native or learned. There is no concept "believes" to be constructed, since ToM is simply the process of putting oneself in another's shoes. 

On this account, to "attribute belief" isn't attribution. Rather the observer feeds pretend inputs (which stand in for the target's beliefs and desires) to her own decision-making machinery, and reads the output off as her prediction about the target @gordon_folk_1986 @heal_replication_2004 @goldman_simulating_2006. The pretend beliefs are usable since they're of the same kind as the target's real beliefs they stand in for @goldman_simulating_2006.

The problem is that, though the simulated run does yield a decision, nothing makes that decision _Sally's_ rather than a stray conclusion of the attributor's own. Nor does anything in it keep the pretend inputs from contaminating what the attributor takes the world to be. So simulationists need to give a containing structure with explicit boundary conditions to the output of one's personal decision-making machinery @nichols_mindreading_2003. 

Also, simulationism doesn't explain the false-belief delay (@timeline). If belief attribution simply uses the observer's own planner, simulationism should predict that false-belief competency arrives soon after the development of the (teleological) planner around the first birthday @gergely_taking_1995, but it's delayed by more than two years. And any simulationist explanation of the delay would be extra-theoretical. So there are few "pure" simulationists @goldman_simulating_2006 @nichols_mindreading_2003.

=== Rational constructivism and the "theory theory" <constructivism>

The constructivist holds that the child is analogous to a scientist @gopnik_scientific_2012 @downes_can_1999: she constructs intuitive theories of mind and world and revises them in light of evidence, by something like the process that drives scientific progress @gopnik_why_1992 @gopnik_words_1997 @wellman_childs_1990. So the child uses domain-general statistical machinery to construct domain-specific structured knowledge. Infants are indeed sensitive to sampling and to statistical evidence in ways that indicate inference to hidden structure, including psychological structure @xu_infants_2013 @wellman_infants_2016 @xu_towards_2019, and children's exploratory behaviour is well described as evidence-gathering aimed at resolving uncertainty about which theory is right @schulz_origins_2012.

On this account the transition from failure to success in the false-belief task is analyzed as an evidence-driven shift between two theories. The infant starts with a simple model, but after encountering evidence inexplainable by that model switches to a more complex one which offers greater explanatory resources @goodman_intuitive_2006.

Rational constructivists specify that Bayesian inference is the formal mechanism of theory change @gopnik_reconstructing_2012 @newcombe_what_2011 @xu_rational_2012. Structured, abstract knowledge, embedded in a probabilistic framework, can be acquired from sparse and noisy data @gopnik_bayesian_2007 @griffiths_probabilistic_2010 @perfors_variability_2010 @griffiths_bayes_2011 @xu_towards_2019 @ullman_bayesian_nodate. Theory formation generally has been modeled as probabilistic inference over systems of related concepts @kemp_probabilistic_2010 @goodman_learning_2011, and theory change has been modelled as stochastic search through a space of theories generated by a grammar @ullman_theory_2010. 

In our analysis, the rational constructivist's theory theory comes closest to explaining the features of ToM laid out in @explanandum. Theories have compositional embeddable terms are constructed cumulatively and learned from data, so the order of acquisition is a consequence of what has already been built. 

The position is a middle way between the first two we surveyed. Nativism posits domain-specific logical symbolic mechanisms, whereas empiricism posits domain-general probabilistic statistical mechanisms. Rational constructivism instead asks "how can domain-general mechanisms of learning and representation build domain-specific systems of knowledge? How can structured symbolic knowledge be acquired through statistical learning?" @tenenbaum_how_2011 @griffiths_bayesian_2024.

Like the empiricist, the constructivist believes that ToM is learned from data. But what is learned is the actual terms and structure of ToM itself, the body that the nativist claims is innate and cannot be learned. So the rational constructivist's position hinges on the assertion that structured symbolic representations "need not be rigid, static, hard-wired, or brittle" but "can grow dynamically and robustly in response to the sparse, noisy data of experience" @tenenbaum_how_2011. Absent a mechanism for growing these theories, the nativist can say that no constructive process exists so that what looks like theory construction is really the maturation of a native module. 

In this thesis we respond to the nativist's claim by counterexample. We propose a model of a process that searches a space of structured hypotheses, selects ones that fit the data on principled grounds, and from correct hypotheses learns new theoretical terms which encode the structure of ToM. 

#load-bib(read("refs2.bib"))
