#import "@preview/illc-mol-thesis:0.2.0": *

#show table.cell.where(y: 0): set text(style: "normal", weight: "bold")
#show table: set par(justify: false)
#set table(stroke: (_, y) => if y == 1 { (top: 0.9pt) } else if y > 1 { (top: 0.2pt) })

#mol-chapter("Learning as Bayesian Program Synthesis")

The mind takes as input a trajectory of bodies through space, and outputs the process that generated the trajectory. The output process is formulated in terms of mental states (beliefs, desires, intentions) that don't appear in the data. The trajectory underdetermines the process, since any behaviour is compatible with indefinitely many belief-desire pairs. So no amount of further observation eliminates all but one.

Stated this way the problem is an instance of a familiar one: given data, entertain hypotheses about the process that generated it, assign each a prior plausibility, and revise those plausibilities as new data comes in. There's already a known answer to the normative question of how such revision ought to proceed, which is Bayes' rule. So our computational-level claim @marr_vision_2010 is that acquiring a theory of mind is the problem of finding the best explanation of observed behaviour, where the best explanation takes into account both its prior plausibility and how well it fits the data.

== Bayesian inference: the logic of learning <sec-bayes>

Say a learner observes data $d$, a trajectory of bodies through space. A learner's task is to choose among possible explanations $cal(H)$ a hypothesis $h$ that best explains the trajectory. The task is to choose the most plausible hypothesis given the data, i.e. to find the hypothesis whose posterior probability $P(h|d)$ is highest. In calculating this quantity, the learner should weigh two things. First, the prior probability $P(h)$: how plausible was hypothesis $h$ before any data $d$ was observed at all? Second, the likelihood $P(d|h)$: how well does hypothesis $h$ account for the data $d$, now that data is available? Bayes' rule specifies how to combine these considerations: 

$
P(h|d) = (P(d|h) P(h)) / (sum_(h' in cal(H)) P(d|h') P(h'))
$

Since the denominator is a normalising constant that doesn't depend on $h$, it can be ignored for the purpose of ranking hypotheses against each other. So we rewrite the equation as the proportion

$
  P(h|d) prop P(d|h) dot P(h)
$

i.e. the _posterior_ probability  $P(h|d)$ of a hypothesis $h$ given data $d$ is proportional to the _likelihood_ $P(d|h)$ of the data $d$ given hypothesis $h$ times the _prior_ probability $P(h)$ of hypothesis $h$ before data $d$ was observed. 

The prior $P(h)$ expresses the a priori plausibility of a hypothesis, i.e. how likely the learner takes $h$ to be, independent of the current observations. So the prior encodes the learner's background knowledge. For example a hypothesis that is outright impossible has prior $P(h)=0$ so it's excluded from $cal(H)$ and no data observation can increase its posterior probability. The prior determines which explanations are more natural, so we can start to generalize from among the indefinitely many hypotheses consistent with the data @xu_word_2007 @frank_using_2009.

Anything can be a prior, since it's just what encodes the learner's background knowledge, assumptions, and preferences. In this thesis the prior we'll focus on is the preference for simplicity. Hypotheses that are short, that reuse existing structure rather than stipulating new structure, will have higher priors than hypotheses that are long and idiosyncratic. This assumption is supported by accounts of human rule-based concept learning @goodman_rational_2008 @chater_simplicity_2003, and by the finding that the difficulty of learning a Boolean concept tracks the length of its shortest logical expression @feldman_minimization_2000. In @sec-programs we'll say precisely how the simplicity of a hypothesis is calculated, after we've said what hypotheses are made of.

The likelihood $P(d|h)$ expresses how probable the observed data would be if the hypothesis were true. In our setting a candidate hypothesis either explains the observed behaviour (i.e. it reproduces the trajectory exactly) or it does not. So the likelihood is all-or-nothing: the data have probability zero $P(d|h)=0$ if they disagree with the hypothesis, and constant probability $P(d|h)=c$ otherwise @goodman_rational_2008. The binary likelihood can only ever eliminate hypotheses, since those with likelihood $P(d|h)=0$ yield posterior $P(h|d)=0$. So once a set of hypotheses all fit the data perfectly (only those with likelihood $P(d|h)=c$ remain), the likelihood can't distinguish between the remaining hypotheses and their ranking is decided entirely by the prior. This division of labour is forced by the domain rather than chosen for convenience. Behaviour here is a trajectory through a discrete grid, and a candidate explanation either reproduces it cell for cell or it does not; there's no residual quantity for a graded likelihood to measure, so partial credit would have to be invented rather than observed (interpreter). Everything the data can do is therefore done by elimination, and every comparison among the survivors falls to the prior.#footnote[This gives up something Bayesian models of generalization normally rely on. Where hypotheses pick out sets of possible observations, a hypothesis that admits fewer observations assigns each of them more probability, so the likelihood favours the most specific hypothesis consistent with the data and does real graded work --- the size principle @tenenbaum_generalization_2001. A deterministic program either emits the observed trajectory or doesn't, so there's no distribution over observations left for that principle to bite on.]

Bayes' rule is a theorem of the probability calculus: given the basic commitment to representing degrees of belief as probabilities, it's the unique coherent way to revise them in light of evidence @jaynes_probability_2003 @mackay_information_nodate. Having stated the computational problem the mind faces, Bayes' rule specifies the ideal solution. And the ideal solution generates predictions that can be checked against what people actually do. If human judgements line up with those predictions, we have grounds for modeling the mind as solving the Bayesian inference problem, and we have an explanation of _why_ people behave as they do rather than merely a description of the fact that they do @griffiths_bayesian_2024 @marr_vision_2010.#footnote[To be clear this claim is at the computational level, not at the algorithmic level. Nobody is saying that a child computes posterior probabilities, or represents the hypothesis space $cal(H)$ explicitly, etc. The claim is that the child's behavior approximates the solution to an inference problem whose ideal form is described by Bayes' rule. It's not an algorithmic-level claim about the procedure by which the child does this, though we'll later introduce an algorithm for approximating this inference.]

== Programs as the hypothesis space <sec-programs>

Bayes' rule doesn't specify what we should define our hypothesis space over, so we can choose the best medium for representing our hypotheses. Since we choose simplicity as our prior, hypotheses should have parts that can be counted so their relative size and complexity can be compared. And a hypothesis must be executable, since the indicator likelihood asks whether running a hypothesis reproduces the observed trajectory (@sec-bayes). A finite learner must have unbounded and systematic capacity (@explanandum), so the hypotheses must be generated by rules of combination @fodor_connectionism_nodate. And also the hypothesis space must admit new terms, since we want to model how a learner acquires the terms that denote mental content (attitudes) even though they don't appear in the data.

These requirements rule out connectionist representations (@empiricism) where a hypothesis is a weight vector or a point in a high-dimensional parameter space @tenenbaum_how_2011. Though they're efficient to update, they lack a natural notion of countable constituent parts so we can't compare their relative sizes, and this is exactly the respect in which such models have been argued to fall short of human learning: they generalize from many examples rather than building explanatory structure from few @lake_building_2016. What we need is a structured symbolic representation like a grammar, predicate logic, relational schemas, or functional programs @griffiths_bayesian_2024 @tenenbaum_how_2011. What we need is a language of thought @fodor_language_2010, where mental representations are symbolic objects combined by syntactic rules and evaluated as a function of their parts @bruner_study_1986 @carey_origin_2011 @siskind_computational_nodate.

Programs are the natural medium for our hypothesis representation. They are compositional, since the value of a composite expression is a function of the values of its parts. And a program admits any expression of the right type in any argument position of that type. Programs can express any effectively computable relation between input and output @turing_computable_1937 @church_unsolvable_1936, and they are executable. And they encode procedural and declarative knowledge in the same format @rule_precis_nodate. There's a long tradition of treating thought this way --- problem solving as symbol manipulation, the mind as a compact program that mirrors the structure of the world @newell_elements_1958 @baum_what_2004 @goodman_concepts_2014. A symbolic medium also leaves the learner free to adopt whatever vocabulary turns out to be useful rather than whatever the modeller happened to supply @gopnik_reconstructing_2012, which is the freedom @sec-hbm will exploit. And furthermore, if knowledge is programs then learning is program induction @flener_introduction_2008 @schmid_aaip_nodate @gulwani_program_2017 which we'll soon make use of.

We adopt the $lambda$-calculus as our program representation formalism, since it's the standard choice for models of learning across domains @piantadosi_bayesian_nodate @zettlemoyer_learning_nodate @piantadosi_bootstrapping_2012 @schmidt_meaning_nodate. Most importantly it gives us $beta$-abstraction as the operation of taking a recurring piece of structure and giving it a name. So this way a learner can come to possess a term that names something that isn't observable in the data, since the new term's content is fixed entirely by what it does in combination the other terms.#footnote[The caveat of @sec-bayes applies here too: we don't claim the mind implements a $lambda$-calculus interpreter, only that its ToM competence is well described as inference over hypotheses that compose, execute, embed, and can be measured for size --- all properties the $lambda$-calculus representation supplies.]

Since our programs are composed of terms of a grammar, a distribution over a grammar's productions induces a distribution over expressions. Since the probability of an expression is the product of the probabilities of the choices made in generating it, longer expressions (involving more choices) get less probability mass. The cost of writing a message in a code optimal for that distribution is the negative log of its probability @shannon_mathematical_nodate, so $h$'s description length under the given grammar is $"DL"(h)=-log P(h)$. So the prior is $P(h) prop e^(-"DL"(h))$. And we have an indicator likelihood for whether executing $h$ reproduces the observed behavior. Substituting into Bayes' rule, the posterior is computed as

$
P(h|d) prop e^(-"DL"(h)) dot bb(1)[h "solves" d]
$

So maximizing the posterior is just minimizing the description length of correct programs. The learner should adopt the program which has the shortest description length of all programs that solve the data (that reproduce the trajectory). This is basically the theory theory (@constructivism): the learner should prefer the simplest theory that accounts for the evidence. And the posterior is similar to the rational rules model, which has been shown to account for human rule-based concept learning @goodman_rational_2008 @chater_simplicity_2003.

This equivalence between probability and code length is what the rest of the thesis measures things in, and it's worth naming. Solomonoff's theory of inductive inference is its ancestor: hypotheses are programs, and each gets prior weight falling exponentially in its length @solomonoff_formal_1964. But that weighting is over programs for a universal machine, so the resulting prior is uncomputable and a learner cannot use it. What a learner can use is the same idea relativized to a particular language, which is the minimum description length principle: inductive inference as the search for the encoding that describes the data in the fewest bits @rissanen_modeling_1978 @grunwald_minimum_2007. Because our likelihood is an indicator, the encoding of the data given the hypothesis costs nothing beyond the hypothesis itself, and MDL collapses into "shortest correct program". It doesn't stay collapsed. When @compression asks whether the learner should adopt a new primitive, the thing being encoded is no longer one trajectory but a whole corpus of solutions, and the code has two parts to pay for — the vocabulary and the corpus written in it — which is MDL in its usual two-part form. So the same principle stated here for a single hypothesis is what will later license changing the language. All quantities in what follows are reported in nats, i.e. description lengths under natural logarithms.

One qualification has to be entered straight away, since it shapes everything that follows. Description length is relative to the primitive vocabulary available, so the same hypothesis may be long under one grammar and short under another that happens to contain the right terms. Simplicity is therefore not a universal measure of a hypothesis' naturalness: as stated so far it inherits whatever vocabulary the modeller chose, and a prior that can be tuned by choosing primitives is not much of a constraint. The classical reply is that this dependence is bounded — description lengths under any two universal languages differ by at most an additive constant, the length of an interpreter for one written in the other, so in the limit the choice of language washes out @li_introduction_2019. That reply is no comfort here. The invariance is asymptotic and the constant is arbitrary, whereas a learner with a finite search budget lives entirely inside the constant: as @sec-search will show, a term's being a few nats cheaper is the difference between a hypothesis being found and never being reached at all. The vocabulary-dependence of description length is not a technicality to be quotiented away, it's the mechanism the thesis is about. @sec-hbm takes this up and argues that the vocabulary need not be stipulated either — that it can be found by the same inference, run one level up.

== Program induction and the search problem <sec-search>

But it's a specification of _what_ the learner should end up with, not a procedure for getting there, and here we start to move from the computational level toward the algorithmic one @marr_vision_2010 @tenenbaum_how_2011. And as soon as we ask how $h^*$ is to be found, the picture becomes much less comfortable.

The trouble is that this optimization is about as badly behaved as an optimization can be. The space is infinite, since a grammar with any recursion generates unboundedly many expressions, and the number of expressions of a given size grows exponentially in that size. There's no gradient to follow, because programs are discrete: there's no meaningful sense in which one is _slightly_ perturbed into another. Worst of all, the binary likelihood gives no partial credit. A program that differs from a correct one by a single token receives exactly the same likelihood as a program picked at random, namely zero. So there's no signal anywhere in the space to hill-climb on, and no way to tell that one is getting warm. The very feature that made the likelihood so clean in @sec-bayes is what makes the search blind.

What one can do, and what the algorithm this thesis uses does, is enumerate hypotheses in decreasing order of prior probability, checking each against the data until one fits. This is the right thing to do in the sense that it finds $h^*$, and it's the only general strategy available given that nothing weaker than a full check tells us whether a candidate works. But the cost is the obvious one. Since $P(h) prop e^(-"DL"(h))$, enumerating every program of description length at most $ell$ takes time on the order of $e^ell$. The time to find a solution is exponential in the description length of that solution under the current library.

This deserves emphasis, because it changes what the prior is doing. In @sec-programs the description length was introduced as a way of _ranking_ hypotheses: shorter means more probable, and among the programs that fit the data, the shortest wins. We can now see that it also determines which hypotheses are _reachable_. A hypothesis that is forty nats long under the learner's current vocabulary is not merely improbable; it is not going to be found. The prior is simultaneously a measure of plausibility and a budget, and a concept's being expressible in the language is no guarantee whatever that it's learnable in the language. This is the move that resource-rational analysis makes general: a model of an agent with finite computation should treat the cost of thinking as part of the problem rather than as an implementation detail to be abstracted away @lieder_resource-rational_2020. Here we get that for free, because the quantity that prices a hypothesis and the quantity that prices the search for it are the same number.

That's the pivot on which the rest of the thesis turns. If what a learner can acquire at a given moment is fixed by what's short in its current vocabulary, and if the vocabulary changes as a result of what has already been acquired, then the ordering of acquisition is not something we have to stipulate. It's a consequence. A concept becomes learnable at the point where earlier learning has made it short enough to be found, which is precisely the cumulative, staged picture that @explanandum demanded and that neither of the alternatives in @perspectives could deliver a mechanism for. The delay between goal attribution and false-belief attribution stops being a fact to be accommodated and becomes something the model can be asked to predict.

There are two ways to attack an exponential search of this kind. The first is to change the language so the target gets shorter: name a recurring piece of structure, add it to the stock of primitives, and every program using it becomes cheaper, so a program previously out of reach can fall within the budget. This is library learning (@sec-hbm, @compression). The second is to abandon enumeration in prior order for enumeration under a learned proposal distribution, trained to guess which primitives a task of this appearance is likely to need. This is amortized inference. The system this thesis builds uses only the first, for reasons given in @no-amortization; it is the first that does the work the argument needs, since it is the one that changes what is _reachable_ rather than merely what is reached sooner. Neither makes the problem tractable in general, and neither is guaranteed to return $h^*$; the claim is only that they make particular problems tractable that were not tractable before. Search over theories, treated in this way as a stochastic process rather than an exhaustive one, has been used to model theory change directly @ullman_theory_nodate.

It's worth noticing that the nativist argument of @nativism can be restated in these terms, and that doing so makes it stronger. The poverty-of-stimulus claim is usually put as a claim about data: there isn't enough of it to fix the target. But the sharper version is a claim about search: even granting the learner all the data it could want, and granting it the right hypothesis space, the target is exponentially far away, so something must be built in to put it within reach. We take this objection seriously, and the answer this thesis offers is not that the search is easy. It's that the distance is not fixed, because the language is not fixed. How a learner could come to change its own language is the subject of the next section.

== Learning the language itself <sec-hbm>

@sec-search left us with a pragmatic reason to want the learner's language to change: the target is exponentially far away, and shortening it is the only way to bring it within reach. That's a reason of convenience, and taken by itself it's a little suspicious. If we're permitted to adjust the vocabulary whenever the search is going badly, then we can make anything learnable by adding a primitive that does the work, and the model explains nothing. What's needed is an account on which changing the language is not a device we apply from outside but something the learner does as part of the same inference it was already doing. This section gives that account, and the claim is that a prior can itself be learned, by exactly the machinery of @sec-bayes applied one level up.

=== The library as an overhypothesis

The move is to stop treating the prior as a fixed input. In the setup of @sec-bayes the learner has a hypothesis space $cal(H)$ and a prior $P(h)$, and both are given. But a prior is a probability distribution, and a probability distribution can be parameterized, and a parameter can be given a distribution of its own and inferred from data like anything else. A hierarchical Bayesian model does this: it posits not a single level of hypotheses but several, with the hypotheses at each level constraining the space and the prior at the level below @gelman_bayesian_1995. Bayesian inference is then run across all levels jointly. In Griffiths' phrase, we get "hypothesis spaces of hypothesis spaces, with priors on priors" @griffiths_bayesian_2024, and the effect is that the prior needed for a specific learning task can itself be learned, over a longer timescale, at the same time as it constrains the learning going on beneath it.

Knowledge at the upper level is _overhypothetical_, in Nelson Goodman's sense @goodman_fact_1983: it's not a hypothesis about the data but a hypothesis about what the hypotheses about the data are like. A standard example shows the shape of it. In categorization, a learner can acquire the overhypothesis that categories of a certain ontological kind tend to be homogeneous in shape but variable in colour, and this abstract knowledge about feature variability then licenses generalizing a new category from a single example @kemp_discovery_2008 @kemp_learning_2007.

The upper level is there doing exactly what @sec-search showed a prior has to do: not merely ranking the lower-level hypotheses but cutting the space of them down to something a learner could search. That's the reason hierarchy is not an optional refinement. For any cognitively realistic task it's simply impossible to enumerate every logically possible hypothesis together with its prior and likelihood; the space is combinatorial @tenenbaum_how_2011. So a learner needs structural constraints that say what kind of thing an explanation could be before it can consider any particular explanation. Structure at the top makes search at the bottom feasible.

One reason to think the upper level is learnable at all is that it is fed by more evidence than the levels beneath it. A specific hypothesis is constrained only by the observations that bear on it directly, whereas an overhypothesis is constrained by every observation in every situation of the relevant kind; so the abstract level pools evidence across scenarios that are, from the point of view of the lower level, unrelated. A child who has watched many people pursue many different goals has seen very little evidence about what any one of them wants, but a great deal about the general shape of the relationship between wanting, seeing and doing. Where the upper level is a parameter with a handful of degrees of freedom, this pooling can be shown to make the abstract posterior concentrate faster than the specific one @kemp_learning_2007 @goodman_learning_2011; where it is a library of $lambda$-terms the space is discrete and unboundedly large, no such convergence result is available, and I claim none. What carries over is the asymmetry rather than the theorem, and it survives because the objective of @compression builds it in: an abstraction is worth adding only if it pays for itself across the whole corpus of solutions.

The example just given is an illustration of the framework rather than an instance of the model I'll build: there the overhypothesis is a small parameter sitting above a lower level of ordinary hypotheses. Here the lower level is programs (@sec-programs), so the distribution to be learned is a distribution over the productions of a grammar, and the upper-level variable is that grammar itself: the stock of primitives, together with the weights on them. This specialization is not an analogy but a well-worked case of the framework, applied to syntactic rules @perfors_learnability_2011, to intuitive theories generated by a probabilistic grammar @ullman_theory_nodate, and to program fragments transferred from solved problems to unsolved ones @liang_learning_nodate. What DreamCoder adds is that the upper-level variable is a library of $lambda$-terms, so that inferring the grammar means acquiring new _concepts_ and not merely reweighting old ones @ellis_dreamcoder_2020.

This also marks a shift in what kind of model we're building. Early Bayesian models addressed the computational level only, characterizing cognition as approximately optimal statistical inference in a fixed environment without saying how the computation was carried out. Hierarchical models sit between the computational and algorithmic levels, describing "cognition as approximately optimal inference in probabilistic models defined over a learner's subjective and dynamically growing mental representations of the world's structure, rather than some objective and fixed world statistics" @tenenbaum_how_2011. The representations grow. That's the feature we need, and it's what @inference will supply a concrete procedure for. It also blurs the tidy division of levels we started from: once the hypothesis space is itself something the learner builds and rebuilds, the question of what the learner is doing can no longer be cleanly separated from the question of what it is doing it _with_. That entanglement is not a defect of the account; it is the part of the account that does the developmental work.

=== Bootstrapping and minimal nativism

We can now state the position this thesis occupies. Learning gets off the ground by combining strong domain-general inferential and representational resources with minimal, skeletal domain-specific knowledge: "strong but domain-general inference and representational resources are aided by weaker, domain-specific perceptual input analyzers" @goodman_learning_2011. This is minimal nativism, and it is a nativism — nobody is claiming the learner starts from nothing. The disagreement with @nativism is over what has to be built in. On the modular view, what's innate includes the attitude concepts themselves, a proprietary representational format for ascribing them, and the agent-directed inferential machinery that operates on it @leslie_pretending_1994. On the view taken here, what's innate is a capacity to represent structured hypotheses, a preference for short ones, a procedure for searching, and enough perceptual apparatus to individuate objects and their motions. Everything specific to the mental is supposed to be constructed.

The construction is cumulative, which is what makes it bootstrapping in Carey's sense @carey_origin_2011 @piantadosi_bootstrapping_2012 rather than a single inference. An abstraction acquired at one stage becomes a term in the language in which the next stage's hypotheses are written, and the cost of using it has already been paid. Applied to our domain, this predicts a particular relationship between the milestones of @timeline: theory of mind functions as the overhypothesis that structures particular attributions, and its components should become available in an order fixed by what each one is built out of. Goal-directedness is available early because it's an abstraction over a great many observed pursuits. Belief is available late because it's an abstraction over goal-directed pursuit together with perceptual access, and it cannot be assembled before its parts exist. The delay of @explanandum, which @nativism accommodates by maturation and @empiricism accommodates by frequency, here falls out of the compositional structure of what's being learned. Whether it actually does so is an empirical question about a particular corpus and a particular library, and one this thesis puts to the test rather than assumes: @sec-order reports where in the run each capacity becomes available and in what order.

There is a second reply to @nativism available here, independent of the delay. A learner acquiring abstract and specific knowledge simultaneously turns out to be almost as efficient as a learner endowed with a fixed and correct abstract theory from the start @goodman_learning_2011. So the developmental evidence that abstract domain knowledge is in place early @wellman_cognitive_1992 does not by itself favour nativism, because that's exactly the pattern a domain-general hierarchical learner produces. Earliness is not evidence of innateness, and that inference is doing a great deal of work in the nativist argument.

What this section has not given is a procedure. Hierarchical Bayesian inference specifies what an ideal learner of abstract knowledge would conclude @tenenbaum_theory-based_2006, and joint inference across levels is at least as intractable as the single-level search of @sec-search — worse, since the space of possible priors is larger than the space of hypotheses. So the situation at the end of this section mirrors the situation at the end of @sec-bayes: we have a well-posed problem and a normative standard for its solution, and no way to reach it. What we need is an algorithm that approximates hierarchical Bayesian inference over the prior, in the specific case where the prior is a distribution over programs and the upper-level hypothesis is a library of primitives.

That algorithm is DreamCoder @ellis_dreamcoder_2020, and I introduce it here only far enough to say what it is: the version this thesis runs is described in @inference, and a reader who wants the full system will find it in @ellis_dreamcoder_2020 rather than paraphrased twice here. It runs in rounds, alternating between the two levels of this section --- solving a batch of tasks under a fixed language, then revising the language in light of what the solutions turn out to have in common. The alternation is not new with it: the same loop was proposed as a model of bootstrapped concept acquisition well before any neural component was added @dechter_bootstrap_nodate.

What DreamCoder contributes is a revision step principled enough to say when a new term is worth keeping, and that step is the answer to the objection this section raised against itself. The vocabulary is not adjusted by a modeller who finds the search going badly; it is adjusted by an objective, and the objective is the two-part code of @sec-programs applied to the language rather than to a single hypothesis: the joint description length of the library together with the corpus written in it @rissanen_modeling_1978. Adding a term shortens every program that uses it and lengthens every program that does not, so a term is kept only if it pays for itself across the corpus as a whole. @compression states the objective and what it selects here.

Since I'll lean on the word "approximates" for the rest of the thesis, it's worth saying now in which respect the approximation falls short, because it isn't only a matter of running out of time. Hierarchical Bayesian inference as described in this section maintains a posterior at every level, so an ideal learner holds a distribution over libraries and never commits to one. The algorithm does not do this. It maximizes rather than integrates, alternating between the two levels and carrying a single library forward from each round — a MAP point estimate of the upper-level variable — and it replaces the posterior over programs with a finite set of the best solutions found for each task. Nothing recovers a library discarded in an earlier round, so the procedure is a hill-climb through the space of languages and can settle on a local optimum that full inference would have avoided. This is the usual price of making hierarchical inference computable and I'll not treat it as a defect, but it does bound the claims available later: when @sec-found reports that a given abstraction was found, the finding is that this search under this corpus arrived at it, not that it's the posterior-optimal library.

What the loop buys, for the argument of this thesis, is the thing @explanandum asked for and @perspectives found missing: a mechanism by which a learner constructs new conceptual terms, adopts them on evidential grounds, and thereby brings within reach concepts that were unreachable before. That is what the theory theory was accused of lacking in @constructivism --- concepts constructed out of earlier concepts, by a procedure that decides what to construct on grounds of compression alone, with the order of construction scheduled by nobody but falling out of what is cheap at each stage. And because reachability is fixed by description length under the current library, while the library changes as a function of what has already been learned, the _order_ in which concepts become available is a consequence of the mechanism rather than a stipulation added to it. The developmental ordering of @timeline becomes something a model of this kind can be asked to predict rather than to accommodate @palmarini_bayesian_2024 --- which is what the rest of the thesis puts to the test.

== What is claimed, and what is not

Fixing the level fixes the scope of the claim, and it is worth being explicit about what falls outside it. We are not studying how a child in fact comes to learn theory of mind. That is the province of developmental and cognitive psychology, and nothing here should be read as a proposal about neural implementation or about the moment-to-moment course of a particular child's development.

Nor is the claim that children run the algorithm just named. ECD, the library-learning system described and implemented in Chapter 4, is offered as an algorithmic-level _realisation_ of the computational-level claim: a demonstration that the problem, so stated, is solvable by a mechanism that begins with no mental vocabulary at all. Its role in the argument is one of sufficiency rather than fidelity. If a learner equipped only with domain-general primitives and a preference for short programs comes to posit belief-like structure, then positing such structure is something a learner _can_ do rather than something it must be given --- and the nativist's inference from "no mechanism has been named" to "no mechanism exists" is blocked. Whether human learners use this mechanism, or some other one that solves the same problem, is a further question that this thesis does not settle.

#load-bib(read("refs.bib"))